local map = vim.keymap.set

map("n", "<leader>w", "<cmd>write<cr>", { desc = "Save file" })
map("n", "<leader>q", "<cmd>bdelete<cr>", { desc = "Close buffer" })
map("n", "<leader>f", function()
  require("telescope.builtin").current_buffer_fuzzy_find()
end, { desc = "Search in file" })
map("n", "<leader>F", function()
  require("telescope.builtin").live_grep()
end, { desc = "Search in project" })
map("n", "<leader>p", function()
  require("telescope.builtin").find_files()
end, { desc = "Find files" })
map("n", "<leader>P", function()
  require("telescope.builtin").oldfiles()
end, { desc = "Recent files" })
map("n", "<leader>b", "<cmd>Neotree toggle filesystem reveal left<cr>", { desc = "Toggle file panel" })
map("n", "<leader>B", "<cmd>Neotree toggle filesystem reveal left<cr>", { desc = "Toggle file panel" })
map("n", "<leader>e", "<cmd>Neotree focus filesystem left<cr>", { desc = "Focus file panel" })
map("n", "<Esc>", "<cmd>nohlsearch<cr>")
map("n", "<S-h>", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
map("n", "<S-l>", "<cmd>bnext<cr>", { desc = "Next buffer" })

map("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
map("n", "gD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
map("n", "gr", vim.lsp.buf.references, { desc = "References" })
map("n", "gi", vim.lsp.buf.implementation, { desc = "Go to implementation" })
map("n", "K", vim.lsp.buf.hover, { desc = "Hover documentation" })
map("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Code action" })
map("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Rename symbol" })
map("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
map("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
map("n", "<leader>d", vim.diagnostic.open_float, { desc = "Line diagnostics" })
